function [fitobj,goodness,output] = gauss_fit2(x,y)
%CREATEFIT(Y)
%  Create a fit.
%
%  Data for '1_sin' fit:
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Sep-2019 17:45:42


%% Fit: '1_sin'.
% [xData, yData] = prepareCurveData( [], y );
% Set up fittype and options.
%  ft = fittype( 'a*exp(-((x-b)/(2*c)).^2)' );
 ft = fittype( 'a*exp(-0.5*((x-b)/c).^2)' );
% ' @(x,pha)x(1)*exp(-((pha-x(2))/(2*x(3))).^2)';
 
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Upper = [Inf Inf  Inf];
opts.Lower = [0 0 0];
opts.StartPoint = [max(y) nanmean(x) nanmean(x)+3];
 y=y';x=x';
 xData=x(find(~isnan(y))); yData=y(~isnan(y));
% Fit model to data.
[fitobj,goodness,output] = fit( xData, yData, ft, opts );
% Plot fit with data.
% figure( 'Name', '1_sin' );
% h = plot( fitresult, xData, yData );
h2=plot(fitobj);
set(h2,'LineWidth',1.5,'Color','k')

% legend( h, 'y', '1_sin', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% ylabel( 'y', 'Interpreter', 'none' );



