function [gof,fitresult2] = gauss_fit(y)
%CREATEFIT(Y)
%  Create a fit.
%
%  Data for '1_sin' fit:
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Sep-2019 17:45:42


%% Fit: '1_sin'.
[xData, yData] = prepareCurveData( [], y );

% Set up fittype and options.
ft = fittype( 'a*exp(-((x-b)/c).^2)' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Upper = [Inf Inf 3];
opts.Lower = [-Inf -Inf -3];
opts.StartPoint = [0.5 6 3];

% Fit model to data.
[fitresult, gof,goodness,output] = fit( xData, yData, ft, opts );
% Plot fit with data.
% figure( 'Name', '1_sin' );
% h = plot( fitresult, xData, yData );
h2=plot(fitresult);
set(h2,'LineStyle',':','LineWidth',1.5,'Color','k')

% legend( h, 'y', '1_sin', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% ylabel( 'y', 'Interpreter', 'none' );



