function [gof] = k_fit(y)
%CREATEFIT(Y)
%  Create a fit.
%
%  Data for '1_sin' fit:
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Sep-2019 17:24:46


%% Fit: '1_sin'.
[xData, yData] = prepareCurveData( [], y );

% Set up fittype and options.
ft = fittype( 'a' );
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.Lower = [mean(y)];
opts.Upper = [mean(y)];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', '1_sin' );
% h = plot( fitresult, xData, yData );
h=plot(fitresult);
set(h,'LineStyle','--','LineWidth',1.5,'Color','k')

% legend( h, 'y', '1_sin', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% ylabel( 'y', 'Interpreter', 'none' );



